services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  elastic:
    networks:
      - elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_USERNAME='elastic'
      - ELASTIC_PASSWORD='elasticpassword'

  kibana:
    networks:
      - elastic
    image: docker.elastic.co/kibana/kibana:8.1.3
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  elastic: